/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Denys Almaral (https://sketchfab.com/denysalmaral)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/low-poly-sea-fishes-with-animations-4dd46cf3a91648469302355cce82e660
title: Low Poly Sea Fishes with Animations
*/

import { useGLTF } from '@react-three/drei'
import { useEffect, useState } from 'react'
import { Bone, Group, MeshStandardMaterial, SkinnedMesh } from 'three'
import { GLTF } from 'three-stdlib'
import { DEG_90 } from '../../lib/util'
import { useMultiTakeAnimations } from '../use-multi-take-actions'

import fishesUrl from '/src/assets/clownfish.glb?url'

interface Props {
  position?:      [number, number, number]
  scale?:         number
  castShadow?:    boolean
  receiveShadow?: boolean
  opacity?:        number
  transparent?:   boolean
}

interface GLTFResult extends GLTF {
  nodes:     { _rootJoint: Bone, Object_7: SkinnedMesh }
  materials: { fishclown: MeshStandardMaterial }
}

export function ClownFish(props: Props) {
  const { castShadow, opacity = 1, position = [0, 0, 0], receiveShadow, scale = 1, transparent = false } = props

  const [root, setRoot] = useState<Group | null>(null)
  const { nodes, materials, animations } = useGLTF(fishesUrl) as GLTFResult
  const actions = useMultiTakeAnimations({ animations, padding: [-30, 30], root })

  useEffect(() => {
    materials.fishclown.opacity = opacity
    materials.fishclown.transparent = transparent
  }, [materials.fishclown, opacity, transparent])

  useEffect(() => {
    actions.swim?.play()
  }, [actions])

  return (
    <group
      ref={setRoot}
      position={position}
      scale={0.1 * scale}
      dispose={null}
      rotation={[-DEG_90, 0, -DEG_90]}
    >
      <primitive object={nodes._rootJoint} />
      <skinnedMesh
        geometry={nodes.Object_7.geometry}
        material={materials.fishclown}
        skeleton={nodes.Object_7.skeleton}
        castShadow={castShadow}
        receiveShadow={receiveShadow}
        frustumCulled={false}
      />
    </group>
  )
}

useGLTF.preload(fishesUrl)
